version: '3'
services:
  streamlit_crypto:
    image: streamlit_crypto
    container_name: crypto_forecast
    build:
      args:
        - username=${USER}
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../src:/home/${USER}/app/src
    init: true
    stdin_open: true
    tty: true    
    restart: unless-stopped

